name: Build Docker Cache

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build-cache:
    name: Build Docker cache
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build linux/x86_64 Docker Cache
        run: docker buildx build --platform linux/x86_64 --rm --push --target build --cache-from fox1t/turborepo-remote-cache:cache -t fox1t/turborepo-remote-cache:cache .
      - name: Build linux/x86_64 Docker Cache
        run: docker buildx build --platform linux/arm64 --rm --push --target build --cache-from fox1t/turborepo-remote-cache:cache -t fox1t/turborepo-remote-cache:cache .
