name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  commitlint:
    name: Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check commit message
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.js
          failOnWarnings: false
          helpURL: https://github.com/ducktors/turborepo-remote-cache#how-to-commit
  
  build:
    runs-on: ${{ matrix.os }}
    name: Build
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7
      - name: Install with pnpm
        run: pnpm install
      - name: Lint code
        run: pnpm lint
      - name: Build
        run: pnpm build

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 7.14.2
      - name: Install with pnpm
        run: pnpm install
      - name: Run tests
        run: pnpm test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: .
      - name: Set correct environment
        run: |
          TAG=${{ steps.package-version.outputs.current-version}}
          echo "TAG=$TAG" >> "$GITHUB_ENV"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: fox1t/turborepo-remote-cache
          flavor: latest=true
          tags: type=raw,value=${{ env.TAG }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/x86_64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
